Fetch Time for 6 is 11.698073
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667693610>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676f7e80>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 11.894648
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676a9d00>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667693eb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 10.600913
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667739100>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676331f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 10.686878
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769ce20>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676a0a60>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 9.844856
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676a0af0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366766ccd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 15.418835
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667633e80>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36675d43a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 12.349951
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366768f9a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667633e80>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 6.288615
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366766c7c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676a0ac0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 10.739726
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676a0a90>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676c1d90>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 20.366659
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769cfa0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676334f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 13.629392
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36677b00a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676a0f10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 17.083412
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366768f100>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676339a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 10.972867
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667701550>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676c1790>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 13.75545
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676a0a30>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36675d4ca0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 14.149627
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676a0a90>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676c1850>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 11.542451
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667701730>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676339d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 9.073074
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667739190>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366766ccd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 19.268891
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676f7bb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676a00a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 7.721957
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36675e5910>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676f3340>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 12.507658
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36675d4880>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676a0880>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 21.126032
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676c1af0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36677011c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 11.745684
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667633910>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667701a30>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 15.816875
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676a0a90>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36675d4430>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 21.272124
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676f31f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667655430>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 18.357389
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36675e5c40>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676f3ac0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 14.132317
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36675d4430>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366768ff10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 10.226703
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676c1b50>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36675d4e80>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 6.338286
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676f3280>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36675e53a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 18.19734
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667655340>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676a0910>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 10.877192
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676f31f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36675d4490>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 7.394654
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667655040>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676c1eb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 7.70825
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676a0040>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676553a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 8.864216
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36675d4130>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676f3bb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 7.517127
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36675e55e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366768f820>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 8.306713
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676a0a30>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676f7e80>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 6.676384
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667693f10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667655280>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 6.709846
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676c1a00>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667693610>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 9.02279
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36675e5970>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676a0c10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 7.571647
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667655a00>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676a9c70>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 7.424747
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676a0280>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36675e5640>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 9.493103
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667739670>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366767e400>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 8.636247
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667633100>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667693ca0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 10.123219
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676f7040>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676a0460>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 6.704666
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366768f0a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769cca0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 7.172969
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36675e5a60>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676f3bb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 7.067854
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36677b0f40>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366768fc70>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 7.239941
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366767e850>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667693eb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 7.408297
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36675e57c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676a0fa0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 5.606573
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667633790>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36675e5670>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 8.250651
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36675e59a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36675d46a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
