Fetch Time for 6 is 11.698073
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667693610>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676f7e80>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 11.894648
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676a9d00>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667693eb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 10.600913
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667739100>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676331f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 10.686878
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769ce20>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676a0a60>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 9.844856
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676a0af0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366766ccd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 15.418835
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667633e80>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36675d43a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 12.349951
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366768f9a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667633e80>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 6.288615
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366766c7c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676a0ac0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 10.739726
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676a0a90>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676c1d90>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 20.366659
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769cfa0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676334f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 13.629392
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36677b00a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676a0f10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 17.083412
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366768f100>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676339a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 10.972867
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667701550>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676c1790>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 13.75545
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676a0a30>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36675d4ca0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 14.149627
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676a0a90>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676c1850>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 11.542451
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667701730>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676339d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 9.073074
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667739190>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366766ccd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 19.268891
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676f7bb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676a00a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 7.721957
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36675e5910>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676f3340>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 12.507658
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36675d4880>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676a0880>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 21.126032
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676c1af0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36677011c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 11.745684
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667633910>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667701a30>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 15.816875
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676a0a90>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36675d4430>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 21.272124
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676f31f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667655430>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 18.357389
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36675e5c40>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676f3ac0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 14.132317
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36675d4430>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366768ff10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 10.226703
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676c1b50>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36675d4e80>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 6.338286
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676f3280>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36675e53a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 18.19734
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667655340>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676a0910>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 10.877192
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676f31f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36675d4490>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 7.394654
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667655040>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676c1eb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 7.70825
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676a0040>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676553a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 8.864216
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36675d4130>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676f3bb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 7.517127
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36675e55e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366768f820>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 8.306713
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676a0a30>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676f7e80>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 6.676384
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667693f10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667655280>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 6.709846
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676c1a00>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667693610>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 9.02279
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36675e5970>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676a0c10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 7.571647
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667655a00>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676a9c70>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 7.424747
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676a0280>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36675e5640>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 9.493103
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667739670>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366767e400>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 8.636247
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667633100>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667693ca0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 10.123219
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676f7040>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676a0460>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 6.704666
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366768f0a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769cca0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 7.172969
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36675e5a60>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676f3bb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 7.067854
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36677b0f40>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366768fc70>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 7.239941
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366767e850>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667693eb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 7.408297
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36675e57c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676a0fa0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 5.606573
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667633790>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36675e5670>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 8.250651
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36675e59a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36675d46a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 7.841213
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366768feb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667633af0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 7.846347
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366768f580>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366767e850>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 5.797722
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676f3940>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36675e5c40>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 8.507538
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667739670>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366767ed60>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 7.833516
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769ca30>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667633eb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 7.837168
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676a9c10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667655070>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 7.050033
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667633160>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769ce20>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 10.751217
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366768f850>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676f3280>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 11.560808
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676553a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366768f730>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 11.533386
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769c1f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676335b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 13.009633
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676a93d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36675e5d30>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 9.608686
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676a9820>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676339a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 6.513891
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769c8e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366768fd30>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 5.554282
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676f3940>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769c280>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 7.029019
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676339a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676a99a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 7.987098
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36675e57f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676c1fa0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 7.49065
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36675e55e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676a93d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 8.07227
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667633460>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769c760>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 5.651752
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676c1940>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667633610>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 6.970208
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676a93d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36675e5640>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 9.031185
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676a0b80>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36675d4e80>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 9.278418
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676c1460>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36675e5370>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 9.15869
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676a9c70>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667633c70>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 7.874683
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769c430>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676a9c10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 9.60414
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36675e5910>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366766c250>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 9.838748
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36675d4a30>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667701d90>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 11.018068
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769c6d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676c1d00>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 9.471166
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676a0fd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676f7e50>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 7.779091
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676332b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36675e5910>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 8.030162
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676c1490>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769c6a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 8.127962
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667701bb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667694eb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 7.296093
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769cc40>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676a0610>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 6.924091
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36675e5610>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667633e80>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 8.184409
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676a98b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36675d4eb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 5.921718
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667701d30>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667633c40>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 7.588329
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676c1100>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769c9a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 9.944852
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676c13d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667633dc0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 11.276234
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667701b20>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36675d4f10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 13.034802
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676a0910>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667701bb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 8.576855
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667633a00>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676c1400>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 7.251781
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769cd00>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667693ee0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 5.590918
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769c430>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676c1400>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 6.779868
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667633d30>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667701cd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 10.603853
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36675d4f10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667633fd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 6.031588
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676c1850>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769c100>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 5.86526
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667693310>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676a9a60>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 7.593354
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36675e5dc0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769cfd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 5.795142
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676c1f40>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667633f10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 8.988797
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676a9a30>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366767ebe0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 10.164023
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769cc70>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36675e5e80>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 9.478142
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366768f1c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676552e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 8.891685
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366768fcd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769c940>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 8.998868
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676c1880>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676f7e80>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 5.370388
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667655e80>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676c1160>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 4.4955
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769c6d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366768f730>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 9.50874
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676a93d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676f3bb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 7.547307
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676552e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366768ffd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 9.818587
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366766c250>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676a0940>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 8.748992
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366767ea30>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769cf40>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 7.620367
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366768f730>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676552e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 5.336745
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676f38e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667694550>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 5.53465
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676a93d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366768f100>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 7.182771
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769c6a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676a0520>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 7.878315
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36675e50a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676945e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 10.493839
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676f37c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676558e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 9.518899
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676a9c70>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667655160>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 9.43203
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667694070>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667694b80>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 6.49029
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366770eca0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676a99a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 7.147256
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36675e5580>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667694b20>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 6.114656
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667693610>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676552e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 11.922963
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676f7670>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667693ca0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 10.944865
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667694c10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36675e5c40>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 8.081783
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676a9d90>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676338b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 6 is 12.470927
Exception called for cameraid 6 and usecase_id 4 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36676a9c10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 6 and usecase_id 13 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36675e5790>: Failed to establish a new connection: [Errno 111] Connection refused'))
